services:
  frontend:
    image: registry.spokayhub.top/efrei-pipelinesfinal-frontend:${IMAGE_TAG:-latest}
    container_name: efrei-pipelinesfinal-frontend-stg
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - ./bx37-frontend-stg.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
